apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sillicon-deployment-kubernetes_version
  namespace: onebean-func
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: sillicon-kubernetes_version
    spec:
      hostAliases:
      containers:
        - name: sillicon-pod-kubernetes_version
          image: nexus.onebean.net:5000/sillicon:latest
          imagePullPolicy: Always
          env:
            - name: JAVA_OPT
              value: "default_vm_args"
          ports:
            - containerPort: 8080
          lifecycle:
            postStart:
              httpGet:
                host: uag-host
                path: devops/addNode?nodeName=sillicon&currentVersion=latest&nodeNamespace=onebean-func
                port: uag-port
                scheme: HTTP
      imagePullSecrets:
        - name: secret-register-auth
